# Generated by Django 4.1.3 on 2022-12-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0003_rename_rank_snack_amount_alter_snack_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='img_url',
            field=models.TextField(default='no image provided'),
        ),
    ]
